version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    working_directory: ~/pyinfer
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run Tests
          command: |
            python -m pytest


workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - dev
                - main